### ISSUE TITLE
Usage of side-channel silent mpz_powm_sec

### ISSUE THREAD

**Issue by jans23** [mirleft/ocaml-nocrypto#140]
I understand that nocrypto uses zarith library which in turn uses GMP. Relevant for RSA, GMP provides mpz_powm and mpz_powm_sec. zaritz (which IMHO is not security-focused) seems to use mpz_powm while only mpz_powm_sec is side-channel resistant. From a security point of view this seems suboptimal. Instead I would prefer nocrypto to use mpz_powm_sec. What is your reasoning for this decision or did I miss anything?

**Comment by jans23** [comment]
As a reference, see [this paper](https://gmplib.org/~tege/modexp-silent.pdf). Especially interesting to me is section 4: 

> A classical approach to these problems is blinding, at least in the context of RSA. [...] Since the secret decryption exponent d is used, a modexp implementation that does not completely protect against leaking the exponent will still be unsafe.

**Comment by cfcs** [comment]
@jans23 a good first step might be to convince Xavier etc to bind it: https://github.com/ocaml/zarith/issues

**Comment by cfcs** [comment]
@jans23 in that case you should write David an email (he doesn't like subscribing to github's issue interface), you find that here:
```
opam info nocrypto | grep author
```

**Comment by pqwy** [comment]
@jans23 

> What is your reasoning for this decision or did I miss anything?

Essentially, no-one has ever demonstrated a remote side-channel attack on blinded RSA. With blinding, you lose control over `m` in `m^d mod n`. All of the attacks I know of are adaptive in `m`.

Granlund's writeup that you are referencing is a theoretical consideration of secret-dependent steps of `powm`, and is trying to come up with an algorithm that has none. The implicit adversary can trace a single execution with absolute precision.

This is in contrast with known attacks. After stating

>  Practical [electromagnetic attacks] attacks using an antenna have been demonstrated, where the key can be extracted from a single operation.

in passing and without a reference, he refers to two prior papers: Kocher (1996) and [Brumley & Boneh (2005)](https://www.sciencedirect.com/science/article/pii/S1389128605000125). I can't find Kocher but it's consistently mentioned as the seminal paper on side-channeling RSA, and the source of blinding. Brumley & Boneh are adaptive:

> For our attack, the key fact about sliding windows is that during the algorithm there are many
multiplications by g, where g is the input ciphertext. By querying on many inputs g the attacker can expose information about bits of the factor q.

They don't even consider the internals of the square-and-multiply exponentiation; they just use it to amplify the timing signal from single Montgomery reductions, which can be used to probe if the operand is close to a factor of the modulus. In this way, they scan for a `q` that divides `n`, recovering a factor, and computing `d` from that. But of course, a blinded implementation cannot be scanned in this way.

Interestingly, they summarize

> We hope this paper demonstrates the necessity of enabling this defense [blinding]. Two other possible defenses are suggested often, but are a second choice to blinding.

and then go on to describe some of the constant-timey-ness that Granlund has later implemented as being this "second choice."

Another prominent paper on side-channeling RSA is [this awesome acoustic attack by Shamir et al (2015)](https://link.springer.com/chapter/10.1007/978-3-662-44371-2_25). It is also adaptive, and even suggests what I call "blinding" as a mitigation:

> *Cipher text randomization.* One countermeasure that is effective in stopping our attack is RSA ciphertext randomization.

In fact, AFAIR this paper prompted GPG to implement it. Other stuff I've seen (PolarSSL, OpenSSL, NSS) also relies on blinding as a large crowbar for RSA timing.

Now, I'm not saying that switching to `Z.powm_sec` is _bad_. `Z.powm` was used originally because it was the only choice, and I might explore the general timing behaviour of `_sec` and its performance, weigh it against the 5%-10% penalty of blinding, and maybe even switch to that.

What I am saying is that there is no evidence that is it _needed_.

@cfcs 

Thanks. Jan pinged me via email in the end.

**Comment by jans23** [comment]
@cfcs I'm not qualified enough to assess this in detail. However, what are the performance penalties for each of both approaches? I guess the approach to use both is not practical, isn't it?

**Comment by cfcs** [comment]
@jans23: `libnettle` uses both, so they seem to think it's practical to think that it's practical.
I don't know what the performance impact is, but I'm guessing the performance of the `_sec` variant would be more platform-dependent than the regular version.
A more important question than performance, IMHO, would be the threat model - I'm not aware of timing attacks that can be executed against a blinded implementation that this would protect against, do you have links to any examples of such? If there's no security gain, I don't think there is much of an argument for making the implementation more complex.

**Comment by jans23** [comment]
@cfcs I don't know any such examples. I'm closing the ticket for now. If somebody has more input on this it could be reopened.
