### ISSUE TITLE
Add {to,from}_hex_string convenience functions

### ISSUE THREAD

**Issue by trevorsummerssmith** [mirleft/ocaml-nocrypto#50]
Currently nocrypto has debug functions that are helpful for debugging. However many protocols use hex encoding to share encrypted objects. Eg AWS authorization http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

I don't know if this should go here or in Cstruct, but I think it would be very useful. Something like:

val cstruct_of_hex_string : string -> Cstruct.t
val hex_string_of_cstruct : Cstruct.t -> string

Happy to submit a pull request if there is a consensus on including an idea like this.

**Comment by nojb** [comment]
Note that `Uncommon.Cs.of_hex` is already there...

**Comment by samoht** [comment]
Could also extend [ocaml-hex](https://github.com/mirage/ocaml-hex) to add `Cstruct` related functions.

**Comment by trevorsummerssmith** [comment]
@nojb oops I missed that. Sorry!

@samoht I'm open to either/both. Given that of_hex is already in Nocrypto it seems natural to add to_hex. Unless, of course, it is really there as a workaround and it should lie in ocaml-hex or elsewhere.

**Comment by hannesm** [comment]
I personally would prefer to have of_hex / to_hex directly in cstruct. maybe also [dotted_hex](https://github.com/mirleft/ocaml-x509/blob/master/lib/x509_pem.ml#L25-L26)!?
The reasoning is that `cstruct` already has a `hexdump` utility, and it sounds wrong to reimplement hex conversions all over (maybe merge it with `ocaml-hex`, which does `string -> hexstring` conversions)...

**Comment by avsm** [comment]
I think putting to/from hex into Cstruct is reasonable, given that it's a major usecase of that library.

**Comment by nojb** [comment]
And could we please add some of the other functions of
`Nocrypto.Uncommon.Cs` (notably `concat` and `equal`) while we are at it?

**Comment by pqwy** [comment]
@nojb Basic [`equal`](https://github.com/mirage/ocaml-cstruct/blob/c964f40ce4f5ae8871dfc7baf17b6fd178c29061/lib/cstruct.ml#L155) is there since `1.6.0`; constant-time version (`~mask:true`) is perhaps misplaced in the general library.

As for the other functions, honestly, I find the number of utilities I need for working with cstructs to be ever-growing. Not sure where to draw the line, exactly.

But `concat` and `append` would probably make sense in the core.
@avsm Want me to cut them out of nocrypto and PR cstruct?

**Comment by avsm** [comment]
Concur about concat and append in cstruct -- pr would be great.

**Comment by trevorsummerssmith** [comment]
@pqwy are you also taking care of a pr for the hex stuff or would you like me to do that? Thanks

**Comment by pqwy** [comment]
Which PR, in the end?

Hex decoding in `nocrypto` is used for storing large published vectors. I don't think a crypto library is quite the place to keep general hex converters because you could obviously want to use that kind of encoding for cstructs without crypto.

I'm also not sure `cstruct` proper is a place for various codecs. `sexplib` is an exception as it travels with the type.

@trevorsummerssmith What I would like to see is what @samoht suggested: [ocaml-hex](https://github.com/mirage/ocaml-hex) extended with cstruct support, ideally with an optional parameter to describe which kinds of characters to ignore, which would make all of pretty-printed hex, dotted hex and strict hex special cases. I would probably reuse that and remove the version here.

**Comment by pqwy** [comment]
It seems that now `ocaml-hex` is taking care of this.
