### ISSUE TITLE
0.5.1 does not work on FreeBSD-9

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-nocrypto#84]
but master does (with `nocrypto-inhibit-modernity`).

`uname -r` is `9.3-RELEASE-p25`
`cc --version` is
```
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd9.3
Thread model: posix
```

**Comment by hannesm** [comment]
@avsm does master work on your OpenBSD as well?

**Comment by pqwy** [comment]
This looks weird. Could you please ask the original source of the bug to provide the full compiler error? The thing is, master makes a difference for the current OpenBSD, because `gcc-4.2`. It could also make a difference for FreeBSD-9 because that comes with `gcc-4.2` too. But it should *not* make a difference for `clang-3.4.1`.

So I'd like to get to the bottom of this.

**Comment by hannesm** [comment]
to solve the mystery, it was a `gcc 4.2.1`, and the problem was (as expected):

```
In file included from src/native/misc.c:1:
src/native/nocrypto.h:15:23: error: x86intrin.h: No such file or directory
cc1: warnings being treated as errors
src/native/misc.c: In function 'xor_into':
src/native/misc.c:9: warning: implicit declaration of function '_mm_storeu_si128'
src/native/misc.c:10: error: '__m128i' undeclared (first use in this function)
src/native/misc.c:10: error: (Each undeclared identifier is reported only once
src/native/misc.c:10: error: for each function it appears in.)
src/native/misc.c:10: error: expected expression before ')' token
```

**Comment by hannesm** [comment]
(closing since this is only a remark that master works well on FreeBSD-9, and there will hopefully be a release in the near future)
