### ISSUE TITLE
nocamlp4

### ISSUE THREAD

**Issue by samoht** [mirleft/ocaml-nocrypto#91]
any plan to remove the camlp4 dependency? There's a new version of sexplib which just uses ppx.

**Comment by Leonidas-from-XIV** [comment]
I believe so, x509 is already being ported over: https://github.com/mirleft/ocaml-x509/pull/75

**Comment by pqwy** [comment]
It's in master, rel pending.

I still wish we had a solution for for `findlib` warning that is DDOSing the build:

```
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/lib/ocaml/compiler-libs, /usr/lib/ocaml
+ /home/self/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -ccopt '--std=c99' -ccopt -Wall -ccopt -Wextra -ccopt -Werror -ccopt -O3 -ccopt -DACCELERATE -ccopt -msse2 -ccopt -maes -w A-4-29-33-40-41-42-43-34-44 -package zarith -package sexplib -package ppx_sexp_conv -package cstruct -I src -o src/nocrypto.cmi src/nocrypto.mli
```

**Comment by rgrinberg** [comment]
`make 2>&1 | grep -v '[WARNING] Interface topdirs'  :D

Out of curiousity, what is the real cause for the warnings? I'd also like to fix them.

**Comment by Leonidas-from-XIV** [comment]
I think @samoht was looking into this, it seems the toplevel directives (topdirs) are apparently part of the compiler and the compiler libs and the file is duplicated.

@pqwy: Thanks for merding; I agree, this should get fixed soon to avoid this useless noise.

**Comment by ivg** [comment]
> I still wish we had a solution for for findlib warning that is DDOSing the build:

There is an environment variable responsible for this: `OCAMLFIND_IGNORE_DUPS_IN`. If you set it

```
     export OCAMLFIND_IGNORE_DUPS_IN=`opam config var lib`/compiler-libs
```

The boring messages will disappear. 

You can also put this into your build system. For example, if you're using `oasis`, then `setup.ml` is a good place to put `Unix.putenv`.

> Out of curiousity, what is the real cause for the warnings? I'd also like to fix them

One of the ppx libraries is using `compiler-libs` library (if I recall it correctly it is `ppx-driver`). It just happens, that this library duplicates topdir module. I suspect that it is already fixed in the trunk.

**Comment by ivg** [comment]
and thank you for the merge!
